### ISSUE TITLE
can't find Swizzler.. could you please set Swizzler to public ?

### ISSUE THREAD

**Issue by michaelmou** [hyperoslo/Sugar#34]

**Comment by zenangst** [comment]
@michaelmou hey, it should be fixed now on `master`. We will release a new version soonish. Thanks for notifying us about this oversight 😎

**Comment by michaelmou** [comment]
：），i think you need to have a test in pod.

**Comment by zenangst** [comment]
@michaelmou we do have tests and specifically for `swizzler` but there we use `@testable import Sugar` which is why this wasn't caught. But no harm done, we will be more careful in the future. Again, thanks for letting us know :sunglasses:

**Comment by michaelmou** [comment]
my pleasure. i thank you too
