### ISSUE TITLE
Please create a 2.3 branch.  

### ISSUE THREAD

**Issue by navisingh** [hyperoslo/Sugar#85]
The only change required to support swift 2.3 is 
    self.init(CGImage: image!.CGImage!)
in the branch instead of
    self.init(CGImage: image.CGImage!)
in the file UIImage+Extensions.swift

**Comment by astrokin** [comment]
@nahitheper you can use this one for now `pod 'Sugar', :git => 'https://github.com/astrokin/Sugar'`

**Comment by zenangst** [comment]
@astrokin mind making a PR towards `swift-2.3` with that fork? 😁

**Comment by astrokin** [comment]
@zenangst thanks for reminding, I forgot about it :) [#86](https://github.com/hyperoslo/Sugar/pull/86)

**Comment by nefarianblack** [comment]
Is this still open? Does this tree helps - https://github.com/hyperoslo/Sugar/tree/swift-2.3?

**Comment by astrokin** [comment]
@nefarianblack we can close it. Thank you.
