### ISSUE TITLE
Can release a tagged version for Swift 3?

### ISSUE THREAD

**Issue by RafaelPlantard** [hyperoslo/Sugar#87]
I'm working with CocoaPods package in there isn't possible point to a branch, is there possible release a tagged version of Sugar package to Swift 3 users?

**Comment by onmyway133** [comment]
@Shakarang @RafaelPlantard the tag `2.0.0` does not work?

**Comment by Shakarang** [comment]
Oh.. @onmyway133 
It works now, I've restarted Xcode and everything is ok.
It showed me around 60 errors.
Sorry about the inconvenience

**Comment by zenangst** [comment]
Closing this one 😎
