### ISSUE TITLE
SegmentationFault

### ISSUE THREAD

**Issue by dbeltram** [hyperoslo/Sugar#91]
With Xcode 8.1 there is segmentation fault `While emitting SIL for 'localizedString'`

**Comment by rx2130** [comment]
I'm having the same problem after upgrading Xcode to 8.1

**Comment by onmyway133** [comment]
@dbeltram @rx2130 FYI, it seems to be fixed in https://github.com/hyperoslo/Sugar/releases/tag/3.0.0 😉
