### ISSUE TITLE
compile failure on Xcode 8.1  (the project compiles, but the spots examples don't).

### ISSUE THREAD

**Issue by navisingh** [hyperoslo/Sugar#92]
I need to comment out this method to make sugar work with the Spots examples.
//
//public func localizedString(_ key: String, _ bundleClass: AnyClass? = nil, comment: String? = nil, arguments: CVarArg...) -> String {
//  return withVaList(arguments) {
//    (NSString(format: localizedString(key, bundleClass, comment: comment), locale: Locale.current, arguments: $0) as String)
//    } as String
//}

**Comment by onmyway133** [comment]
@navisingh Hi, this maybe the same as https://github.com/hyperoslo/Sugar/issues/91, https://github.com/hyperoslo/Sugar/issues/89. Update to 3.0.0 should fix the problem
